service: serverless-nodejs-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
           path: /
           method: get
      - httpApi:
           path: /hello
           method: get
      - httpApi:
           path: /me
           method: get
